### PR TITLE
Added Role change function

### PR DESCRIPTION
**Pull request by monster010**

### CODE REVIEW

**Review by markusmarkusz — CHANGES_REQUESTED** [review]
Please use spaces like it is in the rest of the code and for the names of the roles please use the TTT translation. The rest is fine. :)

**Comment by monster010** [comment]
Replaced Tabs with spaces and using the TTT translation. =)

**Comment by markusmarkusz** [comment]
I decided to use my old version of it. Specifically, to keep the function of changing the role optional.
I would be happy if you could test the version and also tell if the DamageLog message works for Tommy's DamageLog.
https://github.com/markusmarkusz/ttt_death_faker/tree/update

**Comment by MinIsMin** [comment]
The Damagelog message works but yellow isn't a good color.
Also, the type "DeathFaker" is too long.

Damagelogs

Damagelog version: Development 3.0

**Comment by markusmarkusz** [comment]
@MinIsMin 
Thanks for your feedback.
I'll change the type to "DF". Or dou you think "BODY" is better?
Which color should I use for the message?

**Comment by MinIsMin** [comment]
@markusmarkusz 
Don't use BODY as it's already used for identifying bodys and would interfere with sorting by type.
I currently do not know all the colors used and will look into it. (I think darkgreen isn't used)

**Comment by markusmarkusz** [comment]
@MinIsMin 
Okay, then I'll use "DF".
If you have a color that would fit for this message, then please tell me.

**Comment by markusmarkusz** [comment]
Everything should work now. The update should be in the next few minutes in the Steam Workshop.

**Pull request closed without merging**
